remote_theme: MicrosoftLearning/Jekyll-Theme
exclude:
  - readme.md
  - .github/

author: Microsoft Learning
twitter_username: mslearning
github_username:  MicrosoftLearning
plugins:
  - jekyll-sitemap
  - jekyll-mentions
  - jemoji
markdown: kramdown
kramdown:
   syntax_highlighter_opts:
      disable : true
